#!/usr/bin/env python3
"""
Debug the image preview functionality step by step.
"""

import sys
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent))

def test_manual_validation_load():
    """Test manual validation widget loading."""
    print("🧪 Testing Manual Validation Widget Load")
    print("=" * 50)
    
    try:
        from tore_matrix_labs.config.settings import Settings
        from tore_matrix_labs.ui.components.manual_validation_widget import ManualValidationWidget
        from tore_matrix_labs.models.document_models import Document, DocumentMetadata
        from datetime import datetime
        
        # Create a settings object
        settings = Settings()
        print("✅ Settings created")
        
        # Can't create widget without QApplication, but check method signatures
        expected_methods = [
            'load_document',
            '_show_preview_image',
            '_on_area_preview_update',
            '_extract_and_display_area_image'
        ]
        
        for method in expected_methods:
            if hasattr(ManualValidationWidget, method):
                print(f"✅ Method {method}: Available")
            else:
                print(f"❌ Method {method}: Missing")
                return False
        
        # Check load_document signature to see if it accepts file_path
        import inspect
        sig = inspect.signature(ManualValidationWidget.load_document)
        params = list(sig.parameters.keys())
        
        if 'file_path' in params:
            print("✅ load_document accepts file_path parameter")
        else:
            print("❌ load_document missing file_path parameter")
            return False
        
        print("✅ Manual validation widget structure correct")
        return True
        
    except Exception as e:
        print(f"❌ Error: {e}")
        return False

def test_classification_dialog_no_naming():
    """Test that classification dialog doesn't allow user naming."""
    print("\n🧪 Testing Classification Dialog (No User Naming)")
    print("=" * 50)
    
    try:
        # Check classification dialog source
        dialog_file = Path(__file__).parent / "tore_matrix_labs" / "ui" / "components" / "manual_validation_widget.py"
        content = dialog_file.read_text()
        
        # Check that name input fields are removed
        if 'QLineEdit' in content and 'name_input' in content:
            print("❌ User naming input still exists")
            return False
        
        if 'automatically generated by the system' in content:
            print("✅ System naming message present")
        else:
            print("❌ System naming message missing")
            return False
        
        if 'user_name' not in content or content.count('user_name') <= 1:  # Only in old comments
            print("✅ user_name references removed")
        else:
            print("❌ user_name references still exist")
            return False
        
        print("✅ Classification dialog has no user naming options")
        return True
        
    except Exception as e:
        print(f"❌ Error: {e}")
        return False

def test_preview_image_logic():
    """Test the preview image display logic."""
    print("\n🧪 Testing Preview Image Logic")
    print("=" * 50)
    
    try:
        # Check that _show_preview_image method has proper error handling
        widget_file = Path(__file__).parent / "tore_matrix_labs" / "ui" / "components" / "manual_validation_widget.py"
        content = widget_file.read_text()
        
        # Check for proper logging and error handling
        if 'logger.error' in content and 'Cannot show preview' in content:
            print("✅ Error logging implemented")
        else:
            print("❌ Error logging missing")
            return False
        
        # Check for file path validation
        if 'current_document' in content and 'current_file_path' in content:
            print("✅ File path validation present")
        else:
            print("❌ File path validation missing")
            return False
        
        # Check for PyMuPDF usage
        if 'fitz.open' in content and 'get_pixmap' in content:
            print("✅ PyMuPDF image extraction implemented")
        else:
            print("❌ PyMuPDF image extraction missing")
            return False
        
        # Check for QPixmap conversion
        if 'QPixmap' in content and 'loadFromData' in content:
            print("✅ QPixmap conversion implemented")
        else:
            print("❌ QPixmap conversion missing")
            return False
        
        print("✅ Preview image logic properly implemented")
        return True
        
    except Exception as e:
        print(f"❌ Error: {e}")
        return False

def test_signal_connections():
    """Test that all signals are properly connected."""
    print("\n🧪 Testing Signal Connections")
    print("=" * 50)
    
    try:
        # Check main window connections
        main_window_file = Path(__file__).parent / "tore_matrix_labs" / "ui" / "main_window.py"
        content = main_window_file.read_text()
        
        # Check for area preview update connection
        if 'area_preview_update.connect' in content:
            print("✅ area_preview_update signal connected")
        else:
            print("❌ area_preview_update signal not connected")
            return False
        
        # Check for manual validation method connection
        if '_on_area_preview_update' in content:
            print("✅ Manual validation preview handler connected")
        else:
            print("❌ Manual validation preview handler not connected")
            return False
        
        # Check PDF viewer file for signal implementation
        pdf_viewer_file = Path(__file__).parent / "tore_matrix_labs" / "ui" / "components" / "pdf_viewer.py"
        pdf_content = pdf_viewer_file.read_text()
        
        if 'area_preview_update = pyqtSignal' in pdf_content:
            print("✅ PDF viewer has area_preview_update signal")
        else:
            print("❌ PDF viewer missing area_preview_update signal")
            return False
        
        print("✅ All signals properly connected")
        return True
        
    except Exception as e:
        print(f"❌ Error: {e}")
        return False

def debug_potential_issues():
    """Debug potential issues with image preview."""
    print("\n🔍 Debugging Potential Issues")
    print("=" * 50)
    
    issues_to_check = [
        ("File path not properly passed to manual validation", "load_document.*file_path"),
        ("Preview method not being called", "_show_preview_image"),
        ("Error in coordinate conversion", "_convert_to_pdf_coordinates"), 
        ("PyMuPDF extraction failing", "fitz.open.*clip"),
        ("QPixmap conversion failing", "pixmap.loadFromData"),
        ("Preview label not updating", "area_preview_label.setPixmap")
    ]
    
    try:
        widget_file = Path(__file__).parent / "tore_matrix_labs" / "ui" / "components" / "manual_validation_widget.py"
        content = widget_file.read_text()
        
        for issue, pattern in issues_to_check:
            import re
            if re.search(pattern, content):
                print(f"✅ {issue}: Code present")
            else:
                print(f"⚠️  {issue}: Code missing/different")
        
        print("\n💡 Debugging Tips:")
        print("   1. Check console logs for 'Loading document:' messages")
        print("   2. Check for 'Cannot show preview:' error messages")
        print("   3. Verify PDF file path is correct")
        print("   4. Test with a simple PDF file first")
        
        return True
        
    except Exception as e:
        print(f"❌ Error: {e}")
        return False

def main():
    """Run image preview debugging tests."""
    print("🚀 TORE Matrix Labs - Image Preview Debug")
    print("=" * 80)
    
    tests = [
        test_manual_validation_load,
        test_classification_dialog_no_naming,
        test_preview_image_logic,
        test_signal_connections,
        debug_potential_issues
    ]
    
    passed = 0
    failed = 0
    
    for test_func in tests:
        try:
            if test_func():
                passed += 1
            else:
                failed += 1
        except Exception as e:
            print(f"💥 Test error: {e}")
            failed += 1
    
    print("\n" + "=" * 80)
    print(f"📊 Test Results: {passed} passed, {failed} failed")
    
    if failed == 0:
        print("🎉 All image preview components are properly implemented!")
        
        print("\n✅ VERIFIED:")
        print("   🔧 Manual validation load method accepts file_path")
        print("   🚫 User naming completely removed (system control only)")
        print("   🖼️  Image preview logic properly implemented")
        print("   📡 All signals connected correctly")
        
        print("\n🔍 DEBUGGING NEXT STEPS:")
        print("   1. Run the application")
        print("   2. Check console for 'Loading document:' messages") 
        print("   3. Try dragging on PDF - look for 'Received preview update:' logs")
        print("   4. Check for any 'Cannot show preview:' errors")
        print("   5. Verify the PDF file is being loaded correctly")
        
        print("\n📋 IF STILL NOT WORKING:")
        print("   • Check that PDF document loads in right panel")
        print("   • Verify manual validation tab is active")
        print("   • Try with a simple, small PDF file")
        print("   • Check console logs for specific error messages")
        
    else:
        print("⚠️  Some image preview components need fixes.")
    
    return failed == 0

if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)