global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # TORE Matrix API metrics
  - job_name: 'torematrix-api'
    static_configs:
      - targets: ['torematrix-api:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Redis metrics (if Redis exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # PostgreSQL metrics (if postgres exporter is added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # MinIO metrics
  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['minio:9000']
    scrape_interval: 30s

  # Unstructured.io API metrics (if available)
  - job_name: 'unstructured'
    static_configs:
      - targets: ['unstructured:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s