caching:
  memory:
    enabled: true
    size_mb: 1024
    ttl_seconds: 3600
    
  disk:
    enabled: true
    path: "/var/cache/torematrix"
    size_gb: 50
    ttl_days: 7
    
  redis:
    enabled: false  # Optional
    host: "localhost"
    port: 6379
    db: 0
    ttl_days: 30
    
  object_storage:
    enabled: false  # Optional
    type: "s3"
    bucket: "torematrix-cache"
    ttl_days: 90
    
  incremental_processing:
    enabled: true
    change_threshold: 0.3  # Reprocess if >30% changed
    page_cache_ttl: 86400  # 24 hours
    
  metrics:
    enabled: true
    report_interval: 300  # 5 minutes